// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cirukyqlmufdzlfkxcjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpcnVreXFsbXVmZHpsZmt4Y2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzczOTYsImV4cCI6MjA3MzExMzM5Nn0.4VYPmz7QlOA2vP9M94QQPI3ovohhBELCxV7e3Z_PiN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});